"""
report.py — assemble ML/RESULTS.md from the one table run_all.py produces
=========================================================================
Reads `ML/results/all_test.json` and the per-configuration evaluations it
points at, so the document cannot drift from the numbers: re-running it after
a new `run_all.py` rewrites every table rather than inviting a hand-edit.

Every row is an independent model, fitted on seeds 1-19, early-stopped on
20-21, and reported on the whole test batch (seeds 22-25, 125 routes).
Nothing is selected on the test set -- the table reports all of them.

    python ML/code/report.py
"""
from __future__ import annotations

import json
import os
import sys

import numpy as np
from scipy import stats

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from ml_style import LBL                                          # noqa: E402
from paper_link import collect_gaps                               # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.abspath(os.path.join(HERE, "..", "results"))
OUT = os.path.abspath(os.path.join(HERE, "..", "RESULTS.md"))
FLOOR = 0.35      # LA's own measured run-to-run median spread, in %

BASELINES = ["LA (look-ahead MILP)", "2SP", "GREEDY", "RO"]


def paired_vs(rows_file, key):
    with open(os.path.join(RESULTS, rows_file)) as fh:
        rows = json.load(fh)
    return np.array([100.0 * (r["duration_h"] - r[key]) / r[key] for r in rows
                     if r.get("route_completed") and r.get(key)
                     and not r.get(f"{key}_infeasible")])


def verdict(v):
    if len(v) < 5:
        return "—", float("nan"), float("nan")
    med = float(np.median(v))
    try:
        p = float(stats.wilcoxon(v)[1])
    except ValueError:
        p = float("nan")
    if not np.isfinite(p) or p >= 0.05:
        return "matches the teacher", med, p
    if abs(med) < FLOOR:
        return f"below the {FLOOR:.2f}% floor", med, p
    return ("faster than teacher" if med < 0 else "slower than teacher"), med, p


def main():
    p = os.path.join(RESULTS, "all_test.json")
    if not os.path.exists(p):
        raise SystemExit("run ML/code/run_all.py first")
    with open(p) as fh:
        cfgs = json.load(fh)

    L, A = [], None
    L = []
    A = L.append
    A("# Results — learned policies for the discrete-event simulator\n")
    A("Every row is an **independent model**: fitted on seeds 1–19 (639 "
      "routes), early-stopped on seeds 20–21, and reported on the **whole "
      "test batch** (seeds 22–25, 125 routes). Nothing is selected on the "
      "test set — the table reports all of them, so the rows are directly "
      "comparable to each other and to the baselines stored in "
      "`solutions/basecase`.\n")
    A("Generated by `python ML/code/report.py` from "
      "`ML/results/all_test.json`.\n")

    # ── gap to the oracle: the manuscript's metric ─────────────────────────
    gaps, base = {}, {}
    for c in cfgs:
        f = c["eval_file"]
        if not os.path.exists(os.path.join(RESULTS, f)):
            continue
        g = collect_gaps(f, student_label=c["display"])
        a, _pen, n_inf = g[c["display"]]
        if len(a):
            gaps[c["display"]] = (a, n_inf, c)
        if not base:
            for k in BASELINES:
                if k in g and len(g[k][0]):
                    base[k] = (g[k][0], g[k][2])

    A("## Gap to the hindsight oracle\n")
    A("The manuscript's own metric (`data_output/paper_gap_stats.csv`, "
      "`figures/basecase/paper_gap_box*.png`), recomputed with "
      "`compile_solutions._annotate_gap_to_oracle`'s exact definition.\n")
    A("| policy | n | gap to oracle | infeasible | vs LA | verdict |")
    A("|---|---:|---:|---:|---:|---|")
    ordered = sorted(gaps.items(), key=lambda kv: np.median(kv[1][0]))
    for label, (a, n_inf, c) in ordered:
        vd, med_la, _p = verdict(paired_vs(c["eval_file"], "LA"))
        A(f"| **{label}** | {len(a)} | {np.median(a):+.2f}% | "
          f"{n_inf} | {med_la:+.2f}% | {vd} |")
    for k, (a, n_inf) in sorted(base.items(), key=lambda kv: np.median(kv[1][0])):
        A(f"| {k} | {len(a)} | {np.median(a):+.2f}% | {n_inf} | — | baseline |")
    A("")
    A(f"A difference from the teacher below **{FLOOR:.2f}%** is not evidence "
      "of anything: that is the look-ahead's own measured run-to-run median "
      "spread on this simulator.\n")

    # ── the configuration table as run ────────────────────────────────────
    A("## Configurations\n")
    A("| tag | guard | vs LA | vs Greedy | penalised | infeasible | TW | ms/dec | what it tests |")
    A("|---|---:|---:|---:|---:|---:|---:|---:|---|")
    for c in cfgs:
        g = "nominal" if c["guard"] is None else str(c["guard"])
        tw = (c.get("tw") or [0, 0])[0]
        A(f"| `{c['tag']}` | {g} | {c.get('med_la', float('nan')):+.2f}% | "
          f"{c.get('med_greedy', float('nan')):+.2f}% | "
          f"{c.get('med_pen', float('nan')):+.2f}% | "
          f"{int(c.get('infeasible', -1))} | {tw} | "
          f"{c.get('ms', float('nan')):.1f} | {c['desc']} |")
    A("")

    # ── infeasibility is the second axis ───────────────────────────────────
    A("## Feasibility\n")
    A("A violation ends the run at that stop, so an infeasible run has no "
      "duration. Infeasible runs are counted, never averaged, and every "
      "percentage above is paired on routes both policies completed — so a "
      "policy is **not** better because it posts a good median over the "
      "routes it happened to finish. Read the gap column and the infeasible "
      "column together.\n")

    A("## Figures\n")
    for f in sorted(os.listdir(os.path.join(HERE, "..", "figures"))):
        if f.endswith(".png"):
            A(f"- `ML/figures/{f}`")
    A("")
    A("## Not included\n")
    A("- **DAgger** — removed from this project entirely.\n"
      "- The `legacy_*` row, when present, is the 2026-08 model run exactly "
      "as it was built (141 features, 772 teacher runs, its own rollout "
      "code). It is *not* a controlled comparison — see `ML/legacy/README.md`. "
      "The controlled test of the same framing is `clf_*`, which holds "
      "features, instances, splits and decision rule fixed.\n")

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(L))
    print(f"wrote {OUT}  ({len(L)} lines, {len(gaps)} configurations)")


if __name__ == "__main__":
    main()
